spring:
  application:
    name: EasyMark
  servlet:
    multipart:
      max-file-size: 50MB
server:
  port: 8080
  servlet:
    session:
      persistent: false
app-config:
  storage:
    base-dir: /Users/stonexthree/Documents/practise/temp/myMarkDoc
    persistence:
      file:
        discussion: discussions.data
        label: label.data
        user: users.data
        doc:
          holder: doc.data
          dir: docs
          collect: collect.data
  security:
    password: D3UUB2z2D4pGnXdw
    salt: 4831a5d7a60dc285
#静态资源相关
static-files:
  security:
    #严格模式；严格模式下的api，会在响应中配置合适当的 http状态码 ， 而不是默认返回 200
    strict-mode:
      #路径匹配
      path-prefix: /files/picture,/files/others